### ISSUE TITLE
Write instructions / package for Arch

### ISSUE THREAD

**Issue by paulfurley** [fluidkeys/fluidkeys#184]
We've had a few requests for Arch GNU/Linux now. I'm unfamiliar with it, although willing to try. I understand there are system packages and user-contributed packages, so we could start with a user contributed package.

@MatthewCroughan can you report back how you got on installing on arch? Did you get round to doing any packaging?

For my reference, here's a previous thread on another repo discussing arch packaging https://github.com/paulfurley/smart-label-printer-slp-linux-driver/issues/5

**Comment by ilf** [comment]
Having an Arch AUR package would be awesome. Creating one is substantially easier than a Debian package:
https://wiki.archlinux.org/index.php/Arch_package_guidelines

**Comment by rubdos** [comment]
I've started writing `fluidkeys-git`. Will update in a few.

**Comment by paulfurley** [comment]
Thanks @rubdos. We've merged the licence, `master` is now officially AGPL :+1: https://github.com/fluidkeys/fluidkeys/pull/225

**Comment by rubdos** [comment]
I've pushed the [AUR package](https://aur.archlinux.org/packages/fluidkeys-git/) that will build from git. As it relies on the recent `Makefile` change, I won't be pushing a version release yet. Give me a ping somewhere when a new version is made that includes that change, and I'll make a versioned package too.

**Comment by paulfurley** [comment]
Thanks @rubdos ! We pushed `0.2.6` earlier today :) I'll be on XMPP most of tomorrow to help out if necessary :D

**Comment by MatthewCroughan** [comment]
![image](https://user-images.githubusercontent.com/26458780/49963047-d69c6980-ff0e-11e8-8e95-1b1c77fcf2d8.png)

Shows up in the AUR on pamac. 

![image](https://user-images.githubusercontent.com/26458780/49963061-e3b95880-ff0e-11e8-8518-6c1b68ab18a5.png)

It then, for some reason, asks to remove `go` in order to install `go-pie`, which presumably means they can't coexist on my system with pacman.

```
Preparing...
Resolving dependencies...
Checking inter-conflicts...
Downloading...
Downloading go-pie-2:1.11.2-2-x86_64.pkg.tar.xz...
Checking keyring...
Checking integrity...
Loading package files...
Checking file conflicts...
Checking available disc space...
Removing go (2:1.11.2-2)...
Installing go-pie (2:1.11.2-2)...
Running post-transaction hooks...
Arming ConditionNeedsUpdate...

Building fluidkeys-git...
Cloning into 'fluidkeys-git'...
remote: Enumerating objects: 4, done.        
remote: Counting objects: 100% (4/4), done.        
remote: Compressing objects: 100% (4/4), done.        
remote: Total 4 (delta 0), reused 4 (delta 0)        
Unpacking objects: 100% (4/4), done.
==> Making package: fluidkeys-git release.r87.g63f3e8e-1 (Thu 13 Dec 2018 19:41:27 GMT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning fluidkeys git repo...
Cloning into bare repository '/media/e/pamac-build/fluidkeys-git/fluidkeys'...
remote: Enumerating objects: 71, done.        
remote: Counting objects: 100% (71/71), done.        
remote: Compressing objects: 100% (54/54), done.        
remote: Total 4958 (delta 30), reused 38 (delta 13), pack-reused 4887        
Receiving objects: 100% (4958/4958), 6.23 MiB | 7.01 MiB/s, done.
Resolving deltas: 100% (2443/2443), done.
==> Validating source files with sha256sums...
    fluidkeys ... Skipped
==> Extracting sources...
  -> Creating working copy of fluidkeys git repo...
Cloning into 'fluidkeys'...
done.
==> Starting prepare()...
/media/e/pamac-build/fluidkeys-git/PKGBUILD: line 27: dep: command not found
==> ERROR: A failure occurred in prepare().
    Aborting...
```

We then run into the same issue as #31, which I did have until the AUR package removed my existing `go` install. I'd go as far as to say this is pretty destructive to the system it's being installed to, since it asks to remove an existing `go` package which could have had a lot of dev work linked to it. A reinstall of `go` with `pacman -S go` will fix that up, since all the files and symlinks are still present on the system.

**Comment by paulfurley** [comment]
Actually @rubdos you should drop the `dep ensure` command from the build steps. When we add or update dependencies, we use `dep ensure` to update the `vendor/` directory, then we commit the result. Our test suite includes `dep check` which double-checks that `vendor` is up to date with the `Gopkg.*` files.

So in theory `dep ensure` should never make any changes. It's not a good idea to run it since if it *did* change `vendor`, the user might end up running third-party dependency code that we've never inspected.

**Comment by MatthewCroughan** [comment]
@paulfurley I just thought I'd describe the full process as it ran. I don't think I'll ever fully understand the dependency loops on Arch. I also had no idea what pie was until you just described it for me.

Imagine `go-pie` is for some reason not suitable as a replacement for `go` on a user's system. For example, an application might depend on `go` and for some reason not treat `go-pie` as a replacement, despite the binaries occupying the same directories and symlinks. This could cause a problem, since I might want to install `fluidkeys` and another application, lets say `solidkeys` at the same time, one wants `go-pie` and the other wants `go`, however both packages can not be installed. It's one of the biggest problems I ever have with some AUR packages and there's no clear answer that I can come up with. Go is niche enough amongst normal users that this won't be a problem, I think.

**Comment by rubdos** [comment]
I'll change the dep to `go` then. Note that the Arch Go package guidelines say:

> There are two go packages in the repositories that you can build towards; go and go-pie. All packages should preferably be built towards go-pie as this enables us to deliver secure binaries. However, as upstream might have bugs, building towards go should be a last resort.

Since `go-pie` `provides=('go')` iirc, putting `go` as dep shouldn't be a problem though.

@paulfurley mind reminding me start of next week to fix these things up, including the new release package?

**Comment by deraffe** [comment]
@rubdos Reminder.

I've been hacking away on the [`PKGBUILD`](https://gist.github.com/deraffe/e09b009b87e332ac3051fe1e669fd888#file-pkgbuild). Not quite satisfied yet, but close. Take what you need.
Unfortunately I ran into #274 while testing.

**Comment by rubdos** [comment]
> I've been hacking away on the [`PKGBUILD`](https://gist.github.com/deraffe/e09b009b87e332ac3051fe1e669fd888#file-pkgbuild). Not quite satisfied yet, but close. Take what you need.

We're not using the `Makefile` anymore? I would feel quite bad to include a list of all `.go` files, especially in a `-git`.

I'm okay with `--exclude release` to determine the version, I've included that.

I honestly think we first need a *way* more robust `Makefile` or other single-command-build system (like Rust has `cargo build --release`, or the typical `PREFIX=... make install`).

@paulfurley Please send me a reminder now and then on XMPP or email about a non `-git` version on the AUR, if it doesn't appear today.

**Comment by rubdos** [comment]
Okay, I've pushed a release version too: https://aur.archlinux.org/packages/fluidkeys/

The annoying part about a release version is that I'll have to update it every now and then. Feel free to nag me (and send out-of-date flags) about that if it doesn't happen the first day or two.

**Comment by paulfurley** [comment]
Fantastic, thank you @rubdos!

@ilf, @MatthewCroughan it'd be great to know how you get on!

**Comment by deraffe** [comment]
> We're not using the `Makefile` anymore? I would feel quite bad to include a list of all `.go` files, especially in a `-git`.

Yup, it's ugly. But I wanted the `namcap` warnings to go away, and that's what the [Go Packaging Guidelines](https://wiki.archlinux.org/index.php/Go_package_guidelines) suggested.
 
> I honestly think we first need a _way_ more robust `Makefile` or other single-command-build system (like Rust has `cargo build --release`, or the typical `PREFIX=... make install`).

Yes, please. Or maybe just patch the Makefile to respect `LDFLAGS` and properly trim the path references?

**Comment by rubdos** [comment]
> Yes, please. Or maybe just patch the Makefile to respect `LDFLAGS` and properly trim the path references?

I feel like this is a non-Arch Linux issue though. If so, would you open a new issue to track `LDFLAGS` compat and trimming?
