### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by zbeekman** [fluidkeys/fluidkeys#200]
It would be nice if FK provided a license. It's open source in that the source is freely visible on GH, but it's not obvious whether one can fork the project or build on it, integrating it into another software package. Not having a license discourages adoption and contribution.

Just my $0.02, do with it what you please. 😄

**Comment by paulfurley** [comment]
Absolutely, this is high up our agenda.

This is loosely coupled to how we decide to build Fluidkeys *the business* (which we'll talk publicly about as we think properly about it). It's only *loosely* coupled because all of the options we've pub-brainstormed have involved `fk` being GPL or AGPL so far.

**Comment by zbeekman** [comment]
I'm not an expert on open source licensing, but I suspect, if you want to keep it open source, the choice of an open source license may deeply affect your business model. Copyleft licenses may restrict your own ability to commercialize products, while more open licenses, like MIT or new BSD3 may expose you to unwanted competition. As copyright holders of the software it is possible to license it in multiple ways, although this may be incompatible with some copyleft licenses, depending on which other ways you are licensing it.

**Comment by paulfurley** [comment]
Thanks for the input @zbeekman 

> Copyleft licenses may restrict your own ability to commercialize products

Do you mean restrict in the sense that we couldn't charge anything *because* we're already giving it away for free? Or some other restriction?

In a previous company, we sold printing machines, and all the accompanying software was GPL (we were  "infected" by Ghostscript, but didn't mind). The GPL placed no restrictions on us to charge whatever we liked for the software. Similarly, our customers were unrestricted in *giving it away to others for free*, if they so wished. But the printing machine was the product - the software was only a component of it.

Perhaps *Fluidkeys the business* is like the printing machine: we run infrastructure like team keyservers that make Fluidkeys the *software* work really well if you're using it as a team.

In that scenario I don't see GPL restricting us, though perhaps it's giving others too many freedoms to compete / make a free team version or something. I'm not sure.

**Comment by zbeekman** [comment]
> Perhaps _Fluidkeys the business_ is like the printing machine: we run infrastructure like team keyservers that make Fluidkeys the _software_ work really well if you're using it as a team.
> 
> In that scenario I don't see GPL restricting us, though perhaps it's giving others too many freedoms to compete / make a free team version or something. I'm not sure.

Yes I agree. The other caveat is that, I think, GPL will restrict you from licensing the software under other open or closed licenses in addition to GPL or at a later date. This problem doesn't exist with BSD-3 or MIT, AFAIK. (But that also makes it easier for a competitor to commercialize, if true.) Caveat: I'm not a license expert, so I may be mistaken.

If FK is a front-end to SaaS, IaaS, etc. it probably doesn't matter tooooo much if you use GPL as long as you don't use the code server-side.

**Comment by paulfurley** [comment]
Thanks for everyone's patience! We (finally) decided to use AGPLv3 for Fluidkeys client :dancer: 

https://github.com/fluidkeys/fluidkeys/pull/225

**Comment by zbeekman** [comment]
No worries! I meant to forward you guys an interesting article: https://fossa.com/blog/which-open-source-license-is-the-best-for-commercialization/

After having read the article above, and having sat in on a DOE seminar on open source licenses (I'll link it here once the slides/materials are published) and hearing what you've shared about your plans/business model, AVPLv3 sounds like the right choice for you.

If/when you want to start accepting 3rd party contributions, you'll want a CLA or, perhaps better yet, a CTA. Any way good luck guys!

**Comment by paulfurley** [comment]
Ooh thanks @zbeekman, I'll read that. And I'm glad you think it's the right choice!

Stay tuned for an exciting next release (0.3) where you can send and receive secrets on the command line... won't be long :smile:

**Comment by wiktor-k** [comment]
I know it's an old thread but I just found it and I think I can add 2 eurocents: (A)GPL doesn't prevent commercialization but as zbeekman mentioned CLA may be useful if you'd like to produce a closed source fork of fluidkeys with some specific feature for one company. As soon as you accept a contribution from someone else you can't make it closed-source with that contribution included (that may be perceived by some people as a benefit).

For example OpenKeychain uses GPL+CLA and they produce closed enterprise version.

Having (A)GPL license without CLA may still have some minor issues, that's why some projects, like Linux kernel and GitLab require [DCO](https://developercertificate.org/).

I don't want to hijack this issue any more but a nice reference in this matters is [Open (Source) for Business book](https://www.amazon.com/Open-Source-Business-Practical-Licensing/dp/1544737645/) written by a lawyer that understands tech.

:wave:

**Comment by paulfurley** [comment]
Thanks @wiktor-k - we've just bought 2 copies of that book, I've been looking for something like this!
