### ISSUE TITLE
macOS Mojave: "Terminal" would like to administer your computer

### ISSUE THREAD

**Issue by dlgb27** [fluidkeys/fluidkeys#250]
fresh install, `fk secret send paul@---.com` immediately prompted with this:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/25516819/50043425-c3eb7700-006b-11e9-8c10-0e2db644d7c6.png">

Fluidkeys is trying to modify the crontab on first run and it looks like Mojave warns about this.

Related to #191

**Comment by paulfurley** [comment]
To clarify, `fk` adds itself to your crontab for the purpose of automatically maintaining a key.

If it doesn't have any key, or any key to maintain automatically, it shouldn't do this.

I *thought* that was the case, but apparently not :/

**Comment by paulfurley** [comment]
I think the real issue here was that Fluidkeys messed with your crontab *straight after first install* ... when it had no reason to.

https://github.com/fluidkeys/fluidkeys/pull/283 fixes this by ensuring we only add ourselves to the crontab if you've actually got a key with automatic maintenance turned on.

I'm going to close this issue, though I suspect we'll need to figure out later how to prime people about the scary dialog they're about to see...
