### ISSUE TITLE
Failed to upload public key: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by rohanaurora** [fluidkeys/fluidkeys#285]
- Fluidkeys 0.3.2
- macOS Mojave
- gpg (GnuPG) 2.2.12

I am unable to complete all steps during ```fk setup```. I believe I do have openssl and ca-certificates installed. What specifically I can do to resolve this error?

```
panic: Failed to publish key: Failed to upload public key: Post https://api.fluidkeys.com/v1/keys: x509: certificate signed by unknown authority

goroutine 1 [running]:
log.Panicf(0x43c822c, 0x19, 0xc0000c1c30, 0x1, 0x1)
	/usr/local/Cellar/go/1.11.4/libexec/src/log/log.go:333 +0xda
main.keyCreate(0xc00020c980, 0x15, 0x110, 0x43b3966)
	/private/tmp/fluidkeys-20190115-28624-12xeyjt/fluidkeys-0.3.3/gopath/src/github.com/fluidkeys/fluidkeys/fluidkeys/keycreate.go:120 +0x572
main.setup(0x0, 0x0, 0x43b8091)
	/private/tmp/fluidkeys-20190115-28624-12xeyjt/fluidkeys-0.3.3/gopath/src/github.com/fluidkeys/fluidkeys/fluidkeys/setup.go:21 +0x173
main.setupSubcommand(0xc00008bc80, 0xc00008bd10)
	/private/tmp/fluidkeys-20190115-28624-12xeyjt/fluidkeys-0.3.3/gopath/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:267 +0x1b5
main.main()
	/private/tmp/fluidkeys-20190115-28624-12xeyjt/fluidkeys-0.3.3/gopath/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:97 +0x33f
pas-raurora-m1:~ raurora$ 
```
[FluidkeyError.log](https://github.com/fluidkeys/fluidkeys/files/2761389/FluidkeyError.log)

**Comment by paulfurley** [comment]
@rohanaurora thanks for reporting this, we haven't seen this before.

This is a layer down from Fluidkeys in Go's TLS library. It seems you got a bad TLS/SSL certificate from https://api.fluidkeys.com. My initial thoughts are that it could be:

1. An out of date certificate store (I'll have to double check which root certificate store Go actually uses).
2. Man-in-the-middle attack on your connection, are you on some corporate internet connection?

Let's try and rule out 2: would you mind posting the output of `curl -vv https://api.fluidkeys.com/` ?

I'm expecting to see Let's Encrypt as the certificate authority:
```
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=api.fluidkeys.com
*  start date: Dec  3 20:25:21 2018 GMT
*  expire date: Mar  3 20:25:21 2019 GMT
*  subjectAltName: host "api.fluidkeys.com" matched cert's "api.fluidkeys.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
```

**Comment by rohanaurora** [comment]
Thanks for the quick response. Here you go - 

```
pas-raurora-m1:~ raurora$ curl -vv https://api.fluidkeys.com/
*   Trying 34.246.221.52...
* TCP_NODELAY set
* Connected to api.fluidkeys.com (34.246.221.52) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=api.fluidkeys.com
*  start date: Dec  3 20:25:21 2018 GMT
*  expire date: Mar  3 20:25:21 2019 GMT
*  subjectAltName: host "api.fluidkeys.com" matched cert's "api.fluidkeys.com"
*  issuer: C=US; ST=California; L=Pasadena; O=Green Dot Corporation; CN=gdc1wcg01.nextestate.com; emailAddress=adminrole@greendotcorp.com
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: api.fluidkeys.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 307 Authentication Required
< Date: Wed, 16 Jan 2019 18:30:54 GMT
< Connection: close
< Via: HTTPS/1.1 gdc1wcg01.nextestate.com
< Cache-Control: no-store
< Content-Type: text/html
< Content-Language: en
< Location: http://gdc1wcg01.nextestate.com:8070/auth/?du=aHR0cHM6Ly9hcGkuZmx1aWRrZXlzLmNvbS8=&ip=MTAuMjEuMi42OTo4MDcw
< Content-Length: 243
< 
<HEAD><TITLE>Authentication Required</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black"><H1>Authentication Required</H1><HR>
<FONT FACE="Helvetica,Arial"><B>
</B></FONT>
<HR>
<!-- default "Authentication Required" response (307) -->
</BODY>
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
pas-raurora-m1:~ raurora$ 
```

**Comment by paulfurley** [comment]
Thanks for the attachment @rohanaurora.

It appears your company *is* doing a man-in-the-middle on your connection.

I've seen this sort of thing before, I'll take a stab at how it probably works:

* There's firewall / proxy / gateway in the network which intercepts the initial TLS connection to `api.fluidkeys.com`. It quickly generates a new certificate `api.fluidkeys.com` and returns that instead.

* The fake certificate will be signed by a root certificate controlled by your company.

* The company's IT admins add their root certificate to each user's computer, so that computer thinks the fake certs are legitimate

* Finally, the firewall opens a legitimate TLS connection to `api.fluidkeys.com`. That was it decrypts your session, looks inside, then re-encrypts it and forwards data bath and forth:

```
Fluidkeys --[TLS: fake cert]--> Firewall --[TLS connection #2]-> api.fluidkeys.com
```

To anyone reading, in case it's not obvious, that means **the IT department can see *everything* everyone does online: passwords, online banking credentials, personal email, the lot**

Now, I'm gonna take a stab and guess that the reason your machine wasn't fooled and you saw this error is that it's probably not a standard corporate build, and doesn't have that root certificate installed. Does that sound right?

Thankfully Fluidkeys uses end-to-end encryption *inside* the TLS session, so even if the connection *was* successfully compromised, your secrets can't be decrypted by anyone but the end recipient.

But breaking TLS does weaken aspects of the security model, so I'm loathe to suggest a workaround make this (correct) security warning go away.

I'd suggest you contact the team responsible (there's an email in your attachment) and make the case against breaking the security model of TLS.

**Comment by rohanaurora** [comment]
That's it, Paul. Thank you for the informative reply. On my personal computer, I was able to install and setup FluidKeys successfully.
